[package]
name = "bondage"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.137"
serde = { version = "*", features = ["derive"]}
subenum = "1.1.2"
ariadne = "0.5.0"
serde_with = "3.12.0"
clap = { version = "4.5.27", features = ["derive"] }
format_serde_error = "0.3.0"
serde_path_to_error = "0.1.16"
miette = { version = "7.4.0", features = ["fancy"] }

[dev-dependencies]
pretty_assertions = "*"
paste = "1.0"
