[package]
name = "bondage"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.137"
serde = { version = "*", features = ["derive"]}
subenum = "1.1.2"
ariadne = "0.5.0"

[dev-dependencies]
pretty_assertions = "*"
paste = "1.0"
