[package]
name = "ir"
version = "0.1.0"
edition = "2024"

[dependencies]
lexicon = { version = "0.1.0", path = "../lexicon" }
num-traits = "0.2.19"
tree-sitter = "0.25.3"
tree-sitter-ana = { version = "0.1.1", path = "../tree-sitter-ana" }
